In [2]:
!pip install geopandas

Keyring is skipped due to an exception: 'keyring.backends'
Collecting geopandas
  Using cached geopandas-0.10.2-py2.py3-none-any.whl (1.0 MB)
Requirement already satisfied: pandas>=0.25.0 in /opt/conda/lib/python3.7/site-packages (from geopandas) (1.3.5)
Collecting shapely>=1.6
  Using cached shapely-2.0.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
Collecting pyproj>=2.2.0
  Using cached pyproj-3.2.1-cp37-cp37m-manylinux2010_x86_64.whl (6.3 MB)
Collecting fiona>=1.8
  Using cached Fiona-1.9.0-cp37-cp37m-manylinux2014_x86_64.whl (17.0 MB)
Requirement already satisfied: attrs>=19.2.0 in /opt/conda/lib/python3.7/site-packages (from fiona>=1.8->geopandas) (22.1.0)
Collecting cligj>=0.5
  Using cached cligj-0.7.2-py3-none-any.whl (7.1 kB)
Collecting munch>=2.3.2
  Using cached munch-2.5.0-py2.py3-none-any.whl (10 kB)
Collecting click-plugins>=1.0
  Using cached click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Collecting click~=8.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Requirement already satisfied: certifi in /opt/conda/lib/python3.7/site-packages (from fiona>=1.8->geopandas) (2022.9.24)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.25.0->geopandas) (2019.3)
Requirement already satisfied: numpy>=1.17.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.25.0->geopandas) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.25.0->geopandas) (2.8.2)
Requirement already satisfied: importlib-metadata in /opt/conda/lib/python3.7/site-packages (from click~=8.0->fiona>=1.8->geopandas) (5.1.0)
Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from munch>=2.3.2->fiona>=1.8->geopandas) (1.14.0)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata->click~=8.0->fiona>=1.8->geopandas) (3.11.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata->click~=8.0->fiona>=1.8->geopandas) (4.4.0)
Installing collected packages: shapely, pyproj, munch, click, cligj, click-plugins, fiona, geopandas
  Attempting uninstall: click
    Found existing installation: Click 7.0
    Uninstalling Click-7.0:
      Successfully uninstalled Click-7.0
Successfully installed click-8.1.3 click-plugins-1.1.1 cligj-0.7.2 fiona-1.9.0 geopandas-0.10.2 munch-2.5.0 pyproj-3.2.1 shapely-2.0.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [3]:
import pandas as pd
import geopandas as gpd
from shapely.wkt import loads
from shapely.geometry import Polygon, LineString, Point

#### Using Google Static Maps
- Reading Data Frame of census tract information. (df_geo_sm) 
- Reading Data Frame of google static maps images interpreted by CNN (df_sm_vector)
- Merge images vectors and indicators information (df_sm)

In [4]:
df_geo_sm = pd.read_csv('df_geo_sm_All_census_tracts.csv')
df_geo_sm

,image_name,NM_MUNICIP,image_lat,image_lon,cluster_lat,cluster_lon,features,area,geometry,setor,Unnamed: 0,lat,long,TIPO,income,longevity,literacy,population,polygon
0,-24.328745942316303_-49.111388246241354_-24.42...,APIAÍ,-24.328746,-49.111388,-24.421470,-48.817357,"{'type': 'center_point', 'coordinates': [-24.3...",MULTIPOLYGON(((-48.5833786383066 -24.337911414...,POINT (-49.11138824624136 -24.328745942316303),350270530000002,51.0,-49.049589,-24.310839,RURAL,0.436439,0.800000,0.964335,339.0,POLYGON ((-49.11138824624136 -24.4214703352307...
1,-24.328745942316303_-49.102875278251105_-24.42...,APIAÍ,-24.328746,-49.102875,-24.421470,-48.817357,"{'type': 'center_point', 'coordinates': [-24.3...",MULTIPOLYGON(((-48.5833786383066 -24.337911414...,POINT (-49.10287527825111 -24.328745942316303),350270530000002,51.0,-49.049589,-24.310839,RURAL,0.436439,0.800000,0.964335,339.0,POLYGON ((-49.10287527825111 -24.4214703352307...
2,-24.320947354200456_-49.102875278251105_-24.42...,APIAÍ,-24.320947,-49.102875,-24.421470,-48.817357,"{'type': 'center_point', 'coordinates': [-24.3...",MULTIPOLYGON(((-48.5833786383066 -24.337911414...,POINT (-49.10287527825111 -24.320947354200452),350270530000002,51.0,-49.049589,-24.310839,RURAL,0.436439,0.800000,0.964335,339.0,POLYGON ((-49.10287527825111 -24.4214703352307...
3,-24.336544530432146_-49.09436231026086_-24.421...,APIAÍ,-24.336545,-49.094362,-24.421470,-48.817357,"{'type': 'center_point', 'coordinates': [-24.3...",MULTIPOLYGON(((-48.5833786383066 -24.337911414...,POINT (-49.094362310260856 -24.336544530432143),350270530000002,51.0,-49.049589,-24.310839,RURAL,0.436439,0.800000,0.964335,339.0,POLYGON ((-49.094362310260856 -24.421470335230...
4,-24.328745942316303_-49.09436231026086_-24.421...,APIAÍ,-24.328746,-49.094362,-24.421470,-48.817357,"{'type': 'center_point', 'coordinates': [-24.3...",MULTIPOLYGON(((-48.5833786383066 -24.337911414...,POINT (-49.094362310260856 -24.328745942316303),350270530000002,51.0,-49.049589,-24.310839,RURAL,0.436439,0.800000,0.964335,339.0,POLYGON ((-49.094362310260856 -24.421470335230...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31354,-25.21950245975443_-49.22441794362258_-25.0764...,RIO BRANCO DO SUL,-25.219502,-49.224418,-25.076465,-49.347577,"{'type': 'center_point', 'coordinates': [-25.2...",MULTIPOLYGON(((-49.4292612039632 -24.904353409...,POINT (-49.224417943622576 -25.21950245975443),412220605000054,850.0,-49.302733,-25.215822,RURAL,0.504002,0.650000,0.891662,523.0,NaN
31355,-24.923200641865506_-49.48692627977073_-25.076...,RIO BRANCO DO SUL,-24.923201,-49.486926,-25.076465,-49.347577,"{'type': 'center_point', 'coordinates': [-24.9...",MULTIPOLYGON(((-49.4292612039632 -24.904353409...,POINT (-49.48692627977073 -24.923200641865506),412220610000001,851.0,-49.482139,-24.989537,URBANO,0.564022,0.683333,0.969136,71.0,NaN
31356,-24.973825915306104_-49.09188100809827_-24.952...,TUNAS DO PARANÁ,-24.973826,-49.091881,-24.952550,-48.902622,"{'type': 'center_point', 'coordinates': [-24.9...",MULTIPOLYGON(((-48.9290799792449 -24.879412890...,POINT (-49.09188100809828 -24.973825915306104),412788205000001,855.0,-49.087273,-24.972205,URBANO,0.573401,0.733333,0.855208,1082.0,NaN
31357,-24.981535188874894_-48.93053954360936_-24.952...,TUNAS DO PARANÁ,-24.981535,-48.930540,-24.952550,-48.902622,"{'type': 'center_point', 'coordinates': [-24.9...",MULTIPOLYGON(((-48.9290799792449 -24.879412890...,POINT (-48.93053954360936 -24.98153518887489),412788205000006,860.0,-48.928630,-24.979127,RURAL,0.513213,0.783333,0.541950,553.0,NaN
31358,-24.981535188874894_-49.09188100809827_-24.952...,TUNAS DO PARANÁ,-24.981535,-49.091881,-24.952550,-48.902622,"{'type': 'center_point', 'coordinates': [-24.9...",MULTIPOLYGON(((-48.9290799792449 -24.879412890...,POINT (-49.09188100809828 -24.98153518887489),412788205000011,865.0,-49.090760,-24.977358,URBANO,0.556493,0.683333,0.853725,538.0,NaN

In [5]:
#cols =['setor','filename'] + ["v{:d}".format(x) for x in range(4096)]
df_sm_vector = pd.read_csv('df_sm_vector_All_census_tracts.csv') #nrows = 1000,
                        #  header = None, names=cols)
df_sm_vector

,setor,filename,v0,v1,v2,v3,v4,v5,v6,v7,...,v4086,v4087,v4088,v4089,v4090,v4091,v4092,v4093,v4094,v4095
0,350270530000002,-24.328745942316303_-49.111388246241354_-24.42...,0.000000,1.905618,0.000000,0.526517,2.065180,0.000000,0.000000,0.0,...,1.117517,0.0,0.000000,0.000000,0.058051,1.766315,0.000000,0.000000,0.0,0.0
1,350270530000002,-24.328745942316303_-49.102875278251105_-24.42...,0.000000,0.649953,0.000000,1.290461,2.982911,0.000000,0.000000,0.0,...,0.000000,0.0,1.026406,0.000000,0.776519,0.587948,0.000000,0.000000,0.0,0.0
2,350270530000002,-24.320947354200456_-49.102875278251105_-24.42...,0.000000,2.562950,0.000000,2.339698,1.017382,0.000000,0.248386,0.0,...,1.283543,0.0,0.171666,0.000000,0.000000,1.551953,0.000000,1.534409,0.0,0.0
3,350270530000002,-24.336544530432146_-49.09436231026086_-24.421...,0.000000,0.513399,0.000000,1.697171,4.216822,0.000000,0.948382,0.0,...,0.000000,0.0,0.552224,0.000000,0.000000,1.310785,0.000000,1.368933,0.0,0.0
4,350270530000002,-24.328745942316303_-49.09436231026086_-24.421...,0.000000,2.549427,0.000000,1.415525,1.230843,0.000000,0.000000,0.0,...,1.635543,0.0,0.743626,0.404047,0.000000,1.715948,0.000000,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31354,412220605000054,-25.21950245975443_-49.22441794362258_-25.0764...,0.000000,1.908568,0.000000,1.565243,2.571487,0.000000,0.597831,0.0,...,0.000000,0.0,1.431506,0.000000,0.000000,1.746018,0.000000,0.000000,0.0,0.0
31355,412220610000001,-24.923200641865506_-49.48692627977073_-25.076...,0.000000,0.393745,0.000000,0.441595,2.621012,0.000000,0.000000,0.0,...,0.471934,0.0,1.528186,0.000000,0.080074,1.684892,0.000000,1.214797,0.0,0.0
31356,412788205000001,-24.973825915306104_-49.09188100809827_-24.952...,0.000000,0.980792,0.000000,1.199829,2.824320,0.000000,0.989288,0.0,...,0.000000,0.0,0.000000,0.473573,0.000000,0.169691,1.390949,0.000000,0.0,0.0
31357,412788205000006,-24.981535188874894_-48.93053954360936_-24.952...,0.319352,2.686559,0.881047,0.912291,1.679019,0.000000,1.452005,0.0,...,0.000000,0.0,0.376603,0.000000,0.395251,1.270226,0.883023,0.000000,0.0,0.0
31358,412788205000011,-24.981535188874894_-49.09188100809827_-24.952...,0.000000,1.744951,0.000000,0.000000,4.298956,0.062738,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,1.506957,0.782979,0.000000,0.0,0.0

In [8]:
df_geo_sm['filename']=df_geo_sm['image_name']

In [9]:
df_sm = df_sm_vector.merge(df_geo_sm[['filename','setor','TIPO','income','longevity','literacy','population']], left_on=['filename','setor'], right_on=['filename','setor'])
df_sm

,setor,filename,v0,v1,v2,v3,v4,v5,v6,v7,...,v4091,v4092,v4093,v4094,v4095,TIPO,income,longevity,literacy,population
0,350270530000002,-24.328745942316303_-49.111388246241354_-24.42...,0.000000,1.905618,0.000000,0.526517,2.065180,0.000000,0.000000,0.0,...,1.766315,0.000000,0.000000,0.0,0.0,RURAL,0.436439,0.800000,0.964335,339.0
1,350270530000002,-24.328745942316303_-49.102875278251105_-24.42...,0.000000,0.649953,0.000000,1.290461,2.982911,0.000000,0.000000,0.0,...,0.587948,0.000000,0.000000,0.0,0.0,RURAL,0.436439,0.800000,0.964335,339.0
2,350270530000002,-24.320947354200456_-49.102875278251105_-24.42...,0.000000,2.562950,0.000000,2.339698,1.017382,0.000000,0.248386,0.0,...,1.551953,0.000000,1.534409,0.0,0.0,RURAL,0.436439,0.800000,0.964335,339.0
3,350270530000002,-24.336544530432146_-49.09436231026086_-24.421...,0.000000,0.513399,0.000000,1.697171,4.216822,0.000000,0.948382,0.0,...,1.310785,0.000000,1.368933,0.0,0.0,RURAL,0.436439,0.800000,0.964335,339.0
4,350270530000002,-24.328745942316303_-49.09436231026086_-24.421...,0.000000,2.549427,0.000000,1.415525,1.230843,0.000000,0.000000,0.0,...,1.715948,0.000000,0.000000,0.0,0.0,RURAL,0.436439,0.800000,0.964335,339.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31354,412220605000054,-25.21950245975443_-49.22441794362258_-25.0764...,0.000000,1.908568,0.000000,1.565243,2.571487,0.000000,0.597831,0.0,...,1.746018,0.000000,0.000000,0.0,0.0,RURAL,0.504002,0.650000,0.891662,523.0
31355,412220610000001,-24.923200641865506_-49.48692627977073_-25.076...,0.000000,0.393745,0.000000,0.441595,2.621012,0.000000,0.000000,0.0,...,1.684892,0.000000,1.214797,0.0,0.0,URBANO,0.564022,0.683333,0.969136,71.0
31356,412788205000001,-24.973825915306104_-49.09188100809827_-24.952...,0.000000,0.980792,0.000000,1.199829,2.824320,0.000000,0.989288,0.0,...,0.169691,1.390949,0.000000,0.0,0.0,URBANO,0.573401,0.733333,0.855208,1082.0
31357,412788205000006,-24.981535188874894_-48.93053954360936_-24.952...,0.319352,2.686559,0.881047,0.912291,1.679019,0.000000,1.452005,0.0,...,1.270226,0.883023,0.000000,0.0,0.0,RURAL,0.513213,0.783333,0.541950,553.0
31358,412788205000011,-24.981535188874894_-49.09188100809827_-24.952...,0.000000,1.744951,0.000000,0.000000,4.298956,0.062738,0.000000,0.0,...,1.506957,0.782979,0.000000,0.0,0.0,URBANO,0.556493,0.683333,0.853725,538.0

In [11]:
df_sm['setor'].nunique()

940

In [12]:
df_sm['income'].isnull().sum()

2120

#### Using Google Street View
- Reading geographic information from cluster in Vale do Ribeira (df_VR)
- Reading google street view crawler information (df_geo_sv)
- Relate image name from crawler with census tract code and indicators, based on lat/long
- Reading Data Frame of google street view images interpreted by CNN (df_sv_vector)
- Merge images vectors and indicators information (df_sv)

In [13]:
df_census_tracts = pd.read_csv('brasil-census-tracts.csv')
df_census_tracts

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3553: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,WKT,ID,CD_GEOCODI,TIPO,CD_GEOCODB,NM_BAIRRO,CD_GEOCODS,NM_SUBDIST,CD_GEOCODD,NM_DISTRIT,...,ID1,layer,path,RENDA,LONG,LITERACY,IDHM_BRAZI,IDHM_BRA_1,IDHM_BRA_2,IDHM_BRA_3
0,MULTIPOLYGON (((-60.8957500655381 -11.35508255...,17182,110009812000003,RURAL,NaN,NaN,11000981200,NaN,110009812,NOVO PARA�SO,...,NaN,11SEE250GC_SIR,/Users/dant/Documents/1-Projetos/7-PARSEC/SETO...,0.586,0.800,0.876,463.0,0.800000,0.876266,0.586029
1,MULTIPOLYGON (((-60.7499935772151 -11.39989561...,17183,110009815000001,URBANO,NaN,NaN,11000981500,NaN,110009815,FLOR DA SERRA,...,NaN,11SEE250GC_SIR,/Users/dant/Documents/1-Projetos/7-PARSEC/SETO...,0.417,0.817,0.857,464.0,0.816667,0.857143,0.416726
2,MULTIPOLYGON (((-60.7298609571081 -11.35738091...,17184,110009815000002,RURAL,NaN,NaN,11000981500,NaN,110009815,FLOR DA SERRA,...,NaN,11SEE250GC_SIR,/Users/dant/Documents/1-Projetos/7-PARSEC/SETO...,0.462,0.800,0.945,465.0,0.800000,0.945082,0.461572
3,MULTIPOLYGON (((-60.9182894903046 -11.29374439...,17185,110009815000003,RURAL,NaN,NaN,11000981500,NaN,110009815,FLOR DA SERRA,...,NaN,11SEE250GC_SIR,/Users/dant/Documents/1-Projetos/7-PARSEC/SETO...,0.544,0.683,0.907,466.0,0.683333,0.907097,0.544350
4,MULTIPOLYGON (((-60.6904707619017 -11.38391361...,17186,110009815000004,RURAL,NaN,NaN,11000981500,NaN,110009815,FLOR DA SERRA,...,NaN,11SEE250GC_SIR,/Users/dant/Documents/1-Projetos/7-PARSEC/SETO...,0.556,0.800,0.876,467.0,0.800000,0.876410,0.556010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316569,MULTIPOLYGON (((-47.8116481500064 -15.86004529...,4450,530010805300153,URBANO,NaN,NaN,53001080530,S�O SEBASTI�O,530010805,BRAS�LIA,...,NaN,53SEE250GC_SIR,/Users/dant/Documents/1-Projetos/7-PARSEC/SETO...,0.855,0.783,0.997,4301.0,0.783333,0.997175,0.855060
316570,MULTIPOLYGON (((-47.8195053438414 -15.86180054...,4451,530010805300154,URBANO,NaN,NaN,53001080530,S�O SEBASTI�O,530010805,BRAS�LIA,...,NaN,53SEE250GC_SIR,/Users/dant/Documents/1-Projetos/7-PARSEC/SETO...,0.969,0.783,1.000,4302.0,0.783333,1.000000,0.968965
316571,MULTIPOLYGON (((-47.817582705394 -15.855563747...,4452,530010805300155,URBANO,NaN,NaN,53001080530,S�O SEBASTI�O,530010805,BRAS�LIA,...,NaN,53SEE250GC_SIR,/Users/dant/Documents/1-Projetos/7-PARSEC/SETO...,0.892,0.733,1.000,4303.0,0.733333,1.000000,0.892159
316572,MULTIPOLYGON (((-47.7840995782322 -15.90136684...,4453,530010805300156,URBANO,NaN,NaN,53001080530,S�O SEBASTI�O,530010805,BRAS�LIA,...,NaN,53SEE250GC_SIR,/Users/dant/Documents/1-Projetos/7-PARSEC/SETO...,0.511,0.500,0.938,4304.0,0.500000,0.937711,0.511095
316573,MULTIPOLYGON (((-47.7859505029865 -15.92525568...,4454,530010805300158,URBANO,NaN,NaN,53001080530,S�O SEBASTI�O,530010805,BRAS�LIA,...,NaN,53SEE250GC_SIR,/Users/dant/Documents/1-Projetos/7-PARSEC/SETO...,0.000,0.350,0.000,4305.0,0.350000,NaN,NaN

In [14]:
gdf = gpd.GeoDataFrame(df_census_tracts, crs= 'epsg:3857', geometry=[loads(pgon) for pgon in df_census_tracts['WKT']])

In [15]:
gdf3857 = gdf.to_crs(3857)  #coordinates in plain degrees

In [16]:
df_VR = pd.read_csv('VR_clusters.csv', delimiter=';')

In [17]:
df_VR

,Unnamed: 0,Cod_setor,lat,long,TIPO,income,longevity,literacy,population
0,0,350270505000001,-48.848982,-24.513062,URBANO,0.606203,0.800000,0.970194,521.0
1,1,350270505000002,-48.846967,-24.511579,URBANO,0.671455,0.850000,0.971920,452.0
2,2,350270505000003,-48.845093,-24.514756,URBANO,0.778504,0.933333,0.975673,299.0
3,3,350270505000004,-48.846954,-24.519240,URBANO,0.808376,0.800000,0.939745,358.0
4,4,350270505000005,-48.841910,-24.522869,URBANO,0.545806,0.816667,0.968134,837.0
...,...,...,...,...,...,...,...,...,...
875,875,412863305000009,-49.350120,-24.719030,RURAL,0.400798,0.750000,0.902424,546.0
876,876,412863305000010,-49.384792,-24.660716,RURAL,0.449906,0.783333,0.900085,570.0
877,877,412863305000011,-49.441333,-24.676312,RURAL,0.461763,0.783333,0.936782,341.0
878,878,412863305000012,-49.493091,-24.678702,RURAL,0.428022,0.750000,0.885842,451.0
879,879,412863305000013,-49.551136,-24.636571,RURAL,0.429378,0.833333,0.907108,423.0

In [18]:
df_geo_sv = pd.read_csv('geo_sv.csv')
df_geo_sv

,city,direction,filename,latitude,longitude,name,pano_id,uf,geometry,setor
0,APIAÍ,0,amYzj4DUMQbgHzB9M3a_WA-0.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.8467829 -24.51469710000001),3.502705e+14
1,APIAÍ,90,amYzj4DUMQbgHzB9M3a_WA-90.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.8467829 -24.51469710000001),3.502705e+14
2,APIAÍ,180,amYzj4DUMQbgHzB9M3a_WA-180.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.8467829 -24.51469710000001),3.502705e+14
3,APIAÍ,270,amYzj4DUMQbgHzB9M3a_WA-270.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.8467829 -24.51469710000001),3.502705e+14
4,APIAÍ,0,LoaIOwDck-H26nB1MZdD7Q-0.jpg,-24.514405,-48.846691,unknown,LoaIOwDck-H26nB1MZdD7Q,unknown,POINT (-48.84669064403143 -24.51440519523027),3.502705e+14
...,...,...,...,...,...,...,...,...,...,...
112363,DOUTOR ULYSSES,270,oSXOgE7j3mV9lfiPJMwySA-270.jpg,-24.646414,-49.425382,unknown,oSXOgE7j3mV9lfiPJMwySA,unknown,POINT (-49.42538241476539 -24.64641441220216),4.128633e+14
112364,DOUTOR ULYSSES,0,VknK6sWJIKFoVDOPr94viA-0.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.41880613831557 -24.62566856991785),4.128633e+14
112365,DOUTOR ULYSSES,90,VknK6sWJIKFoVDOPr94viA-90.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.41880613831557 -24.62566856991785),4.128633e+14
112366,DOUTOR ULYSSES,180,VknK6sWJIKFoVDOPr94viA-180.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.41880613831557 -24.62566856991785),4.128633e+14
112367,DOUTOR ULYSSES,270,VknK6sWJIKFoVDOPr94viA-270.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.41880613831557 -24.62566856991785),4.128633e+14

In [19]:
gdf_geo_sv = gpd.GeoDataFrame(df_geo_sv, crs= 'epsg:3857', geometry=[loads(pgon) for pgon in df_geo_sv['geometry']])
gdf_geo_sv

,city,direction,filename,latitude,longitude,name,pano_id,uf,geometry,setor
0,APIAÍ,0,amYzj4DUMQbgHzB9M3a_WA-0.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14
1,APIAÍ,90,amYzj4DUMQbgHzB9M3a_WA-90.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14
2,APIAÍ,180,amYzj4DUMQbgHzB9M3a_WA-180.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14
3,APIAÍ,270,amYzj4DUMQbgHzB9M3a_WA-270.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14
4,APIAÍ,0,LoaIOwDck-H26nB1MZdD7Q-0.jpg,-24.514405,-48.846691,unknown,LoaIOwDck-H26nB1MZdD7Q,unknown,POINT (-48.847 -24.514),3.502705e+14
...,...,...,...,...,...,...,...,...,...,...
112363,DOUTOR ULYSSES,270,oSXOgE7j3mV9lfiPJMwySA-270.jpg,-24.646414,-49.425382,unknown,oSXOgE7j3mV9lfiPJMwySA,unknown,POINT (-49.425 -24.646),4.128633e+14
112364,DOUTOR ULYSSES,0,VknK6sWJIKFoVDOPr94viA-0.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14
112365,DOUTOR ULYSSES,90,VknK6sWJIKFoVDOPr94viA-90.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14
112366,DOUTOR ULYSSES,180,VknK6sWJIKFoVDOPr94viA-180.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14
112367,DOUTOR ULYSSES,270,VknK6sWJIKFoVDOPr94viA-270.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14

In [20]:
#df_geo_sv['geometry']
#gdf3857['geometry'].contains()
df_geo_sv_join = gdf_geo_sv.sjoin(gdf3857[['geometry','CD_GEOCODI']], how="inner", predicate='intersects')
df_geo_sv_join

,city,direction,filename,latitude,longitude,name,pano_id,uf,geometry,setor,index_right,CD_GEOCODI
0,APIAÍ,0,amYzj4DUMQbgHzB9M3a_WA-0.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14,173149,350270505000016
1,APIAÍ,90,amYzj4DUMQbgHzB9M3a_WA-90.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14,173149,350270505000016
2,APIAÍ,180,amYzj4DUMQbgHzB9M3a_WA-180.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14,173149,350270505000016
3,APIAÍ,270,amYzj4DUMQbgHzB9M3a_WA-270.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14,173149,350270505000016
4,APIAÍ,0,LoaIOwDck-H26nB1MZdD7Q-0.jpg,-24.514405,-48.846691,unknown,LoaIOwDck-H26nB1MZdD7Q,unknown,POINT (-48.847 -24.514),3.502705e+14,173149,350270505000016
...,...,...,...,...,...,...,...,...,...,...,...,...
112363,DOUTOR ULYSSES,270,oSXOgE7j3mV9lfiPJMwySA-270.jpg,-24.646414,-49.425382,unknown,oSXOgE7j3mV9lfiPJMwySA,unknown,POINT (-49.425 -24.646),4.128633e+14,257280,412863305000010
112364,DOUTOR ULYSSES,0,VknK6sWJIKFoVDOPr94viA-0.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14,257280,412863305000010
112365,DOUTOR ULYSSES,90,VknK6sWJIKFoVDOPr94viA-90.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14,257280,412863305000010
112366,DOUTOR ULYSSES,180,VknK6sWJIKFoVDOPr94viA-180.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14,257280,412863305000010
112367,DOUTOR ULYSSES,270,VknK6sWJIKFoVDOPr94viA-270.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14,257280,412863305000010

In [21]:
df_geo_sv_join['Compare'] = df_geo_sv_join['setor'] == df_geo_sv_join['CD_GEOCODI']
df_geo_sv_join

,city,direction,filename,latitude,longitude,name,pano_id,uf,geometry,setor,index_right,CD_GEOCODI,Compare
0,APIAÍ,0,amYzj4DUMQbgHzB9M3a_WA-0.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14,173149,350270505000016,True
1,APIAÍ,90,amYzj4DUMQbgHzB9M3a_WA-90.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14,173149,350270505000016,True
2,APIAÍ,180,amYzj4DUMQbgHzB9M3a_WA-180.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14,173149,350270505000016,True
3,APIAÍ,270,amYzj4DUMQbgHzB9M3a_WA-270.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14,173149,350270505000016,True
4,APIAÍ,0,LoaIOwDck-H26nB1MZdD7Q-0.jpg,-24.514405,-48.846691,unknown,LoaIOwDck-H26nB1MZdD7Q,unknown,POINT (-48.847 -24.514),3.502705e+14,173149,350270505000016,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112363,DOUTOR ULYSSES,270,oSXOgE7j3mV9lfiPJMwySA-270.jpg,-24.646414,-49.425382,unknown,oSXOgE7j3mV9lfiPJMwySA,unknown,POINT (-49.425 -24.646),4.128633e+14,257280,412863305000010,True
112364,DOUTOR ULYSSES,0,VknK6sWJIKFoVDOPr94viA-0.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14,257280,412863305000010,True
112365,DOUTOR ULYSSES,90,VknK6sWJIKFoVDOPr94viA-90.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14,257280,412863305000010,True
112366,DOUTOR ULYSSES,180,VknK6sWJIKFoVDOPr94viA-180.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14,257280,412863305000010,True
112367,DOUTOR ULYSSES,270,VknK6sWJIKFoVDOPr94viA-270.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14,257280,412863305000010,True

In [22]:
df_geo_sv_join[df_geo_sv_join['Compare']==False]

,city,direction,filename,latitude,longitude,name,pano_id,uf,geometry,setor,index_right,CD_GEOCODI,Compare
2220,APIAÍ,0,hUbA4K15PVI4unoUzJBfaQ-0.jpg,-24.347133,-48.849975,unknown,hUbA4K15PVI4unoUzJBfaQ,unknown,POINT (-48.850 -24.347),NaN,205572,354300625000005,False
2221,APIAÍ,90,hUbA4K15PVI4unoUzJBfaQ-90.jpg,-24.347133,-48.849975,unknown,hUbA4K15PVI4unoUzJBfaQ,unknown,POINT (-48.850 -24.347),NaN,205572,354300625000005,False
2222,APIAÍ,180,hUbA4K15PVI4unoUzJBfaQ-180.jpg,-24.347133,-48.849975,unknown,hUbA4K15PVI4unoUzJBfaQ,unknown,POINT (-48.850 -24.347),NaN,205572,354300625000005,False
2223,APIAÍ,270,hUbA4K15PVI4unoUzJBfaQ-270.jpg,-24.347133,-48.849975,unknown,hUbA4K15PVI4unoUzJBfaQ,unknown,POINT (-48.850 -24.347),NaN,205572,354300625000005,False
2328,BARRA DO TURVO,0,rLlS3ISpRI5hhs4-ud2ykw-0.jpg,-25.059924,-48.570177,unknown,rLlS3ISpRI5hhs4-ud2ykw,unknown,POINT (-48.570 -25.060),NaN,241637,410400605000040,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112187,DOUTOR ULYSSES,270,B9oQkwocE0_jBg-7LuzlGA-270.jpg,-24.519028,-49.458573,unknown,B9oQkwocE0_jBg-7LuzlGA,unknown,POINT (-49.459 -24.519),NaN,256241,412630607000004,False
112188,DOUTOR ULYSSES,0,I1dj_JnzvySDYmuHAAGbPQ-0.jpg,-24.519123,-49.453610,unknown,I1dj_JnzvySDYmuHAAGbPQ,unknown,POINT (-49.454 -24.519),NaN,256241,412630607000004,False
112189,DOUTOR ULYSSES,90,I1dj_JnzvySDYmuHAAGbPQ-90.jpg,-24.519123,-49.453610,unknown,I1dj_JnzvySDYmuHAAGbPQ,unknown,POINT (-49.454 -24.519),NaN,256241,412630607000004,False
112190,DOUTOR ULYSSES,180,I1dj_JnzvySDYmuHAAGbPQ-180.jpg,-24.519123,-49.453610,unknown,I1dj_JnzvySDYmuHAAGbPQ,unknown,POINT (-49.454 -24.519),NaN,256241,412630607000004,False
112191,DOUTOR ULYSSES,270,I1dj_JnzvySDYmuHAAGbPQ-270.jpg,-24.519123,-49.453610,unknown,I1dj_JnzvySDYmuHAAGbPQ,unknown,POINT (-49.454 -24.519),NaN,256241,412630607000004,False

In [23]:
df_geo_sv_VR = df_geo_sv_join.merge(df_VR, left_on='CD_GEOCODI', right_on='Cod_setor', how='left')
df_geo_sv_VR

,city,direction,filename,latitude,longitude,name,pano_id,uf,geometry,setor,...,Compare,Unnamed: 0,Cod_setor,lat,long,TIPO,income,longevity,literacy,population
0,APIAÍ,0,amYzj4DUMQbgHzB9M3a_WA-0.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14,...,True,15.0,3.502705e+14,-48.846972,-24.513441,URBANO,0.701822,0.850000,0.990476,292.0
1,APIAÍ,90,amYzj4DUMQbgHzB9M3a_WA-90.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14,...,True,15.0,3.502705e+14,-48.846972,-24.513441,URBANO,0.701822,0.850000,0.990476,292.0
2,APIAÍ,180,amYzj4DUMQbgHzB9M3a_WA-180.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14,...,True,15.0,3.502705e+14,-48.846972,-24.513441,URBANO,0.701822,0.850000,0.990476,292.0
3,APIAÍ,270,amYzj4DUMQbgHzB9M3a_WA-270.jpg,-24.514697,-48.846783,unknown,amYzj4DUMQbgHzB9M3a_WA,unknown,POINT (-48.847 -24.515),3.502705e+14,...,True,15.0,3.502705e+14,-48.846972,-24.513441,URBANO,0.701822,0.850000,0.990476,292.0
4,APIAÍ,0,LoaIOwDck-H26nB1MZdD7Q-0.jpg,-24.514405,-48.846691,unknown,LoaIOwDck-H26nB1MZdD7Q,unknown,POINT (-48.847 -24.514),3.502705e+14,...,True,15.0,3.502705e+14,-48.846972,-24.513441,URBANO,0.701822,0.850000,0.990476,292.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112363,DOUTOR ULYSSES,270,oSXOgE7j3mV9lfiPJMwySA-270.jpg,-24.646414,-49.425382,unknown,oSXOgE7j3mV9lfiPJMwySA,unknown,POINT (-49.425 -24.646),4.128633e+14,...,True,876.0,4.128633e+14,-49.384792,-24.660716,RURAL,0.449906,0.783333,0.900085,570.0
112364,DOUTOR ULYSSES,0,VknK6sWJIKFoVDOPr94viA-0.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14,...,True,876.0,4.128633e+14,-49.384792,-24.660716,RURAL,0.449906,0.783333,0.900085,570.0
112365,DOUTOR ULYSSES,90,VknK6sWJIKFoVDOPr94viA-90.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14,...,True,876.0,4.128633e+14,-49.384792,-24.660716,RURAL,0.449906,0.783333,0.900085,570.0
112366,DOUTOR ULYSSES,180,VknK6sWJIKFoVDOPr94viA-180.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14,...,True,876.0,4.128633e+14,-49.384792,-24.660716,RURAL,0.449906,0.783333,0.900085,570.0
112367,DOUTOR ULYSSES,270,VknK6sWJIKFoVDOPr94viA-270.jpg,-24.625669,-49.418806,unknown,VknK6sWJIKFoVDOPr94viA,unknown,POINT (-49.419 -24.626),4.128633e+14,...,True,876.0,4.128633e+14,-49.384792,-24.660716,RURAL,0.449906,0.783333,0.900085,570.0

In [24]:
df_geo_sv_VR[df_geo_sv_VR['Cod_setor'].isna()][['city','geometry','CD_GEOCODI']]

                  city                 geometry       CD_GEOCODI
2292             APIAÍ  POINT (-48.850 -24.347)  354300625000005
2293             APIAÍ  POINT (-48.850 -24.347)  354300625000005
2294             APIAÍ  POINT (-48.850 -24.347)  354300625000005
2295             APIAÍ  POINT (-48.850 -24.347)  354300625000005
2448    BARRA DO TURVO  POINT (-48.570 -25.060)  410400605000040
...                ...                      ...              ...
112323  DOUTOR ULYSSES  POINT (-49.459 -24.519)  412630607000004
112324  DOUTOR ULYSSES  POINT (-49.454 -24.519)  412630607000004
112325  DOUTOR ULYSSES  POINT (-49.454 -24.519)  412630607000004
112326  DOUTOR ULYSSES  POINT (-49.454 -24.519)  412630607000004
112327  DOUTOR ULYSSES  POINT (-49.454 -24.519)  412630607000004

[1540 rows x 3 columns]

In [25]:
pd.set_option('max_columns', 25)

In [26]:
gdf[gdf['CD_GEOCODI']==354300625000005]

,WKT,ID,CD_GEOCODI,TIPO,CD_GEOCODB,NM_BAIRRO,CD_GEOCODS,NM_SUBDIST,CD_GEOCODD,NM_DISTRIT,CD_GEOCODM,NM_MUNICIP,NM_MICRO,NM_MESO,ID1,layer,path,RENDA,LONG,LITERACY,IDHM_BRAZI,IDHM_BRA_1,IDHM_BRA_2,IDHM_BRA_3,geometry
205572,MULTIPOLYGON (((-48.8399943919542 -24.29560733...,99797,354300625000005,RURAL,NaN,NaN,35430062500,NaN,354300625,ITAB�A,3543006,RIBEIR�O BRANCO,CAP�O BONITO,ITAPETININGA,34244.0,35SEE250GC_SIR,/Users/dant/Documents/1-Projetos/7-PARSEC/SETO...,0.453,0.75,0.944,32193.0,0.75,0.943953,0.452626,"MULTIPOLYGON (((-48.840 -24.296, -48.840 -24.2..."

In [27]:
df_sv_vector = pd.read_csv('vgg_features_sv.csv')#, nrows = 1000)
df_sv_vector

,filename,direction,v0,v1,v2,v3,v4,v5,v6,v7,v8,v9,...,v4084,v4085,v4086,v4087,v4088,v4089,v4090,v4091,v4092,v4093,v4094,v4095
0,../images/Ur0pYB2-_GRdWdiDs7fLDw-0.jpg,0,0.000000,1.274044,1.207465,0.060032,0.000000,0.000000,0.090868,0.00000,0.000000,0.000000,...,1.542214,0.0,0.246125,0.000000,0.000986,0.000000,0.0,0.000000,3.779225,0.000000,1.367594,0.0
1,../images/Ur0pYB2-_GRdWdiDs7fLDw-90.jpg,90,0.000000,1.944860,1.041572,1.170711,0.000000,0.000000,1.441398,0.00000,0.000000,0.000000,...,0.956663,0.0,0.860608,0.039688,0.000000,0.000000,0.0,0.000000,1.857175,0.594794,1.653337,0.0
2,../images/Ur0pYB2-_GRdWdiDs7fLDw-180.jpg,180,0.000000,1.983598,0.000000,0.977700,0.000000,0.000000,0.192336,0.00000,0.627662,0.000000,...,0.000000,0.0,0.000000,0.564503,0.000000,0.000000,0.0,2.264348,1.461094,0.000000,0.000000,0.0
3,../images/Ur0pYB2-_GRdWdiDs7fLDw-270.jpg,270,0.000000,0.164109,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.226122,0.0,0.000000,0.950160,0.000000,0.000000,0.0,1.291897,1.798183,0.000000,1.054379,0.0
4,../images/aUv0C32j9GB_skLEOHDsSw-0.jpg,0,0.000000,0.801934,2.099401,0.000000,1.636646,0.000000,0.169160,0.00000,0.000000,0.000000,...,3.350963,0.0,0.000000,2.128648,0.370794,0.000000,0.0,0.000000,3.017967,2.031153,1.673920,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112363,../images/X-bYVruUMA4yGMqImWGIJQ-270.jpg,270,0.044728,0.000000,1.205815,2.970326,0.744207,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.543213,0.0,0.122861,1.455261,0.857080,0.000000,0.0,2.174360,2.655334,0.000000,0.000000,0.0
112364,../images/WEJX2wf0pWRdeT21xkl2Xg-0.jpg,0,1.010405,0.854102,2.158837,0.028532,1.241926,0.252556,2.071068,0.14139,0.000000,0.000000,...,1.083005,0.0,0.000000,2.525876,0.000000,0.000000,0.0,0.000000,2.733738,0.000000,1.804710,0.0
112365,../images/WEJX2wf0pWRdeT21xkl2Xg-90.jpg,90,0.000000,2.466843,1.078898,0.621070,2.343587,0.488201,1.155512,0.00000,0.000000,0.955930,...,2.741141,0.0,0.493072,1.314766,0.202898,0.000000,0.0,0.041083,0.355666,1.707421,1.603968,0.0
112366,../images/WEJX2wf0pWRdeT21xkl2Xg-180.jpg,180,0.000000,0.068113,1.504246,0.656156,0.904255,0.000000,1.258630,0.00000,0.000000,0.280363,...,1.951587,0.0,0.000000,1.490852,0.000000,0.248110,0.0,0.653702,1.507798,0.000000,0.923584,0.0
112367,../images/WEJX2wf0pWRdeT21xkl2Xg-270.jpg,270,0.163088,0.335939,2.069864,0.000000,1.718546,0.000000,2.116167,0.00000,0.000000,0.000000,...,1.033651,0.0,0.000000,2.630031,0.000000,0.068713,0.0,0.387579,2.352553,0.089231,1.705103,0.0

In [28]:
df_geo_sv_VR['setor']=df_geo_sv_VR['CD_GEOCODI']

In [29]:
df_sv_vector['filename']=df_sv_vector['filename'].str[10:]
df_sv = df_sv_vector.merge(df_geo_sv_VR[['filename', 'setor']], left_on='filename', right_on='filename')
df_sv

,filename,direction,v0,v1,v2,v3,v4,v5,v6,v7,v8,v9,...,v4085,v4086,v4087,v4088,v4089,v4090,v4091,v4092,v4093,v4094,v4095,setor
0,Ur0pYB2-_GRdWdiDs7fLDw-0.jpg,0,0.000000,1.274044,1.207465,0.060032,0.000000,0.000000,0.090868,0.00000,0.000000,0.000000,...,0.0,0.246125,0.000000,0.000986,0.000000,0.0,0.000000,3.779225,0.000000,1.367594,0.0,410020205000005
1,Ur0pYB2-_GRdWdiDs7fLDw-90.jpg,90,0.000000,1.944860,1.041572,1.170711,0.000000,0.000000,1.441398,0.00000,0.000000,0.000000,...,0.0,0.860608,0.039688,0.000000,0.000000,0.0,0.000000,1.857175,0.594794,1.653337,0.0,410020205000005
2,Ur0pYB2-_GRdWdiDs7fLDw-180.jpg,180,0.000000,1.983598,0.000000,0.977700,0.000000,0.000000,0.192336,0.00000,0.627662,0.000000,...,0.0,0.000000,0.564503,0.000000,0.000000,0.0,2.264348,1.461094,0.000000,0.000000,0.0,410020205000005
3,Ur0pYB2-_GRdWdiDs7fLDw-270.jpg,270,0.000000,0.164109,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.0,0.000000,0.950160,0.000000,0.000000,0.0,1.291897,1.798183,0.000000,1.054379,0.0,410020205000005
4,aUv0C32j9GB_skLEOHDsSw-0.jpg,0,0.000000,0.801934,2.099401,0.000000,1.636646,0.000000,0.169160,0.00000,0.000000,0.000000,...,0.0,0.000000,2.128648,0.370794,0.000000,0.0,0.000000,3.017967,2.031153,1.673920,0.0,352990605000010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112363,X-bYVruUMA4yGMqImWGIJQ-270.jpg,270,0.044728,0.000000,1.205815,2.970326,0.744207,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.0,0.122861,1.455261,0.857080,0.000000,0.0,2.174360,2.655334,0.000000,0.000000,0.0,354260205000010
112364,WEJX2wf0pWRdeT21xkl2Xg-0.jpg,0,1.010405,0.854102,2.158837,0.028532,1.241926,0.252556,2.071068,0.14139,0.000000,0.000000,...,0.0,0.000000,2.525876,0.000000,0.000000,0.0,0.000000,2.733738,0.000000,1.804710,0.0,352042605000017
112365,WEJX2wf0pWRdeT21xkl2Xg-90.jpg,90,0.000000,2.466843,1.078898,0.621070,2.343587,0.488201,1.155512,0.00000,0.000000,0.955930,...,0.0,0.493072,1.314766,0.202898,0.000000,0.0,0.041083,0.355666,1.707421,1.603968,0.0,352042605000017
112366,WEJX2wf0pWRdeT21xkl2Xg-180.jpg,180,0.000000,0.068113,1.504246,0.656156,0.904255,0.000000,1.258630,0.00000,0.000000,0.280363,...,0.0,0.000000,1.490852,0.000000,0.248110,0.0,0.653702,1.507798,0.000000,0.923584,0.0,352042605000017
112367,WEJX2wf0pWRdeT21xkl2Xg-270.jpg,270,0.163088,0.335939,2.069864,0.000000,1.718546,0.000000,2.116167,0.00000,0.000000,0.000000,...,0.0,0.000000,2.630031,0.000000,0.068713,0.0,0.387579,2.352553,0.089231,1.705103,0.0,352042605000017

In [30]:
df_sv[df_sv['setor'].isna()]

Empty DataFrame
Columns: [filename, direction, v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, v33, v34, v35, v36, v37, v38, v39, v40, v41, v42, v43, v44, v45, v46, v47, v48, v49, v50, v51, v52, v53, v54, v55, v56, v57, v58, v59, v60, v61, v62, v63, v64, v65, v66, v67, v68, v69, v70, v71, v72, v73, v74, v75, v76, v77, v78, v79, v80, v81, v82, v83, v84, v85, v86, v87, v88, v89, v90, v91, v92, v93, v94, v95, v96, v97, ...]
Index: []

[0 rows x 4099 columns]

# Combine
- a) Dado 1 imagem do SM, capturar todas imagens SV para aquele setor, combinados de 5 em 5. 
- b) Quando não houver SV, colocar vetor com tudo FF.

In [31]:
df = df_sm.merge(df_sv, left_on='setor', right_on='setor', how='left')

In [32]:
df

,setor,filename_x,v0_x,v1_x,v2_x,v3_x,v4_x,v5_x,v6_x,v7_x,v8_x,v9_x,...,v4084_y,v4085_y,v4086_y,v4087_y,v4088_y,v4089_y,v4090_y,v4091_y,v4092_y,v4093_y,v4094_y,v4095_y
0,350270530000002,-24.328745942316303_-49.111388246241354_-24.42...,0.0,1.905618,0.0,0.526517,2.065180,0.000000,0.000000,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,350270530000002,-24.328745942316303_-49.102875278251105_-24.42...,0.0,0.649953,0.0,1.290461,2.982911,0.000000,0.000000,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,350270530000002,-24.320947354200456_-49.102875278251105_-24.42...,0.0,2.562950,0.0,2.339698,1.017382,0.000000,0.248386,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,350270530000002,-24.336544530432146_-49.09436231026086_-24.421...,0.0,0.513399,0.0,1.697171,4.216822,0.000000,0.948382,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,350270530000002,-24.328745942316303_-49.09436231026086_-24.421...,0.0,2.549427,0.0,1.415525,1.230843,0.000000,0.000000,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
806459,412788205000011,-24.981535188874894_-49.09188100809827_-24.952...,0.0,1.744951,0.0,0.000000,4.298956,0.062738,0.000000,0.0,0.0,0.0,...,0.634178,0.000000,0.066244,0.000000,0.000000,0.000000,0.0,0.000000,2.942308,6.936145,1.070476,0.000000
806460,412788205000011,-24.981535188874894_-49.09188100809827_-24.952...,0.0,1.744951,0.0,0.000000,4.298956,0.062738,0.000000,0.0,0.0,0.0,...,3.479262,0.000000,0.000000,0.345365,0.000000,0.000000,0.0,0.000000,0.956469,0.924641,0.000000,2.639096
806461,412788205000011,-24.981535188874894_-49.09188100809827_-24.952...,0.0,1.744951,0.0,0.000000,4.298956,0.062738,0.000000,0.0,0.0,0.0,...,6.302904,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
806462,412788205000011,-24.981535188874894_-49.09188100809827_-24.952...,0.0,1.744951,0.0,0.000000,4.298956,0.062738,0.000000,0.0,0.0,0.0,...,0.253580,1.500292,0.000000,0.000000,0.494643,0.000000,0.0,1.690741,3.194525,0.000000,0.644739,1.460737
806463,412788205000011,-24.981535188874894_-49.09188100809827_-24.952...,0.0,1.744951,0.0,0.000000,4.298956,0.062738,0.000000,0.0,0.0,0.0,...,2.349547,0.000000,0.000000,0.000000,1.125956,0.714944,0.0,0.000000,2.246962,0.000000,0.795234,0.000000

In [35]:
OUT_FILE   = 'df_combine_All_census_tract.csv'

In [ ]:
df.to_csv(OUT_FILE, mode='a', index=None)

In [42]:
a = 1

In [43]:
a = 2

In [44]:
a=3

In [41]:
a = 4