In [2]:
!pip install geopandas

/opt/conda/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/opt/conda/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting geopandas
  Using cached geopandas-0.10.2-py2.py3-none-any.whl (1.0 MB)
Collecting shapely>=1.6
  Using cached Shapely-1.8.1.post1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.0 MB)
Requirement already satisfied: pandas>=0.25.0 in /opt/conda/lib/python3.7/site-packages (from geopandas) (1.0.1)
Collecting fiona>=1.8
  Using cached Fiona-1.8.21-cp37-cp37m-manylinux2014_x86_64.whl (16.7 MB)
Collecting pyproj>=2.2.0
  Using cached pyproj-3.2.1-cp37-cp37m-manylinux2010_x86_64.whl (6.3 MB)
Collecting click-plugins>=1.0
  Using cached click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from fiona>=1.8->geopandas) (59.5.0)
Requirement already satisfied: certifi in /opt/conda/lib/python3.7/site-packages (from fiona>=1.8->geopandas) (2021.10.8)
Requirement already satisfied: attrs>=17 in /opt/conda/lib/python3.7/site-packages (from fiona>=1.8->geopandas) (19.3.0)
Collecting munch
  Using cached munch-2.5.0-py2.py3-none-any.whl (10 kB)
Collecting cligj>=0.5
  Using cached cligj-0.7.2-py3-none-any.whl (7.1 kB)
Requirement already satisfied: click>=4.0 in /opt/conda/lib/python3.7/site-packages (from fiona>=1.8->geopandas) (7.0)
Requirement already satisfied: six>=1.7 in /opt/conda/lib/python3.7/site-packages (from fiona>=1.8->geopandas) (1.14.0)
Requirement already satisfied: numpy>=1.13.3 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.25.0->geopandas) (1.20.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.25.0->geopandas) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /opt/conda/lib/python3.7/site-packages (from pandas>=0.25.0->geopandas) (2019.3)
Installing collected packages: munch, cligj, click-plugins, shapely, pyproj, fiona, geopandas
Successfully installed click-plugins-1.1.1 cligj-0.7.2 fiona-1.8.21 geopandas-0.10.2 munch-2.5.0 pyproj-3.2.1 shapely-1.8.1.post1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/opt/conda/bin/python -m pip install --upgrade pip' command.

In [3]:
import os
import shutil
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point, Polygon
from tqdm.notebook import tqdm

In [8]:
BASE_DIR = '..'
RANDOM_SEED = 7 # for reproducibility
COUNTRIES_DIR = os.path.join(BASE_DIR, '-ImageAquisition', 'data','processed')
MUNICIPALITIES_DIR = os.path.join(BASE_DIR, '2-ImageAquisition', 'data','muncipalities')


PROCESSED = os.path.join(BASE_DIR, '3-TrainCNN')
PROCESSED_DATA_DIR = os.path.join(BASE_DIR, '1-ValeRibeira-Data', 'data','processed')

# these relate to training the CNN to predict nightlights
CNN_TRAIN_IMAGE_DIR = os.path.join(BASE_DIR, 'data', 'cnn_images')
CNN_SAVE_DIR = os.path.join(BASE_DIR, 'models')

CONS_PC_COLUMN = 'RendaIDHM'

In [9]:
df_vr = pd.read_csv(os.path.join(PROCESSED_DATA_DIR, 'VR_clusters.csv'),sep=';')
df_vr

,Unnamed: 0,Cod_setor,lat,long,TIPO,income,longevity,literacy,population
0,0,350270505000001,-48.848982,-24.513062,URBANO,0.606203,0.800000,0.970194,521.0
1,1,350270505000002,-48.846967,-24.511579,URBANO,0.671455,0.850000,0.971920,452.0
2,2,350270505000003,-48.845093,-24.514756,URBANO,0.778504,0.933333,0.975673,299.0
3,3,350270505000004,-48.846954,-24.519240,URBANO,0.808376,0.800000,0.939745,358.0
4,4,350270505000005,-48.841910,-24.522869,URBANO,0.545806,0.816667,0.968134,837.0
...,...,...,...,...,...,...,...,...,...
875,875,412863305000009,-49.350120,-24.719030,RURAL,0.400798,0.750000,0.902424,546.0
876,876,412863305000010,-49.384792,-24.660716,RURAL,0.449906,0.783333,0.900085,570.0
877,877,412863305000011,-49.441333,-24.676312,RURAL,0.461763,0.783333,0.936782,341.0
878,878,412863305000012,-49.493091,-24.678702,RURAL,0.428022,0.750000,0.885842,451.0
879,879,412863305000013,-49.551136,-24.636571,RURAL,0.429378,0.833333,0.907108,423.0

In [7]:
df = pd.read_csv(os.path.join(PROCESSED, 'df_geo.csv'))
df

,image_name,NM_MUNICIP,image_lat,image_lon,cluster_lat,cluster_lon,features,area,geometry,setor,Unnamed: 0,lat,long,TIPO,income,longevity,literacy,population
0,-24.328745942316303_-49.111388246241354_-24.42...,APIAÍ,-24.328746,-49.111388,-24.421470,-48.817357,"{'type': 'center_point', 'coordinates': [-24.3...",MULTIPOLYGON(((-48.5833786383066 -24.337911414...,POINT (-49.11138824624136 -24.328745942316303),350270530000002,51.0,-49.049589,-24.310839,RURAL,0.436439,0.800000,0.964335,339.0
1,-24.328745942316303_-49.102875278251105_-24.42...,APIAÍ,-24.328746,-49.102875,-24.421470,-48.817357,"{'type': 'center_point', 'coordinates': [-24.3...",MULTIPOLYGON(((-48.5833786383066 -24.337911414...,POINT (-49.10287527825111 -24.328745942316303),350270530000002,51.0,-49.049589,-24.310839,RURAL,0.436439,0.800000,0.964335,339.0
2,-24.320947354200456_-49.102875278251105_-24.42...,APIAÍ,-24.320947,-49.102875,-24.421470,-48.817357,"{'type': 'center_point', 'coordinates': [-24.3...",MULTIPOLYGON(((-48.5833786383066 -24.337911414...,POINT (-49.10287527825111 -24.320947354200452),350270530000002,51.0,-49.049589,-24.310839,RURAL,0.436439,0.800000,0.964335,339.0
3,-24.336544530432146_-49.09436231026086_-24.421...,APIAÍ,-24.336545,-49.094362,-24.421470,-48.817357,"{'type': 'center_point', 'coordinates': [-24.3...",MULTIPOLYGON(((-48.5833786383066 -24.337911414...,POINT (-49.094362310260856 -24.336544530432143),350270530000002,51.0,-49.049589,-24.310839,RURAL,0.436439,0.800000,0.964335,339.0
4,-24.328745942316303_-49.09436231026086_-24.421...,APIAÍ,-24.328746,-49.094362,-24.421470,-48.817357,"{'type': 'center_point', 'coordinates': [-24.3...",MULTIPOLYGON(((-48.5833786383066 -24.337911414...,POINT (-49.094362310260856 -24.328745942316303),350270530000002,51.0,-49.049589,-24.310839,RURAL,0.436439,0.800000,0.964335,339.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31146,-24.70493405897603_-49.22055342451572_-24.6253...,DOUTOR ULYSSES,-24.704934,-49.220553,-24.625378,-49.392223,"{'type': 'center_point', 'coordinates': [-24.7...",MULTIPOLYGON(((-49.4038750791893 -24.498103035...,POINT (-49.220553424515714 -24.70493405897603),412863305000006,872.0,-49.267460,-24.712696,RURAL,0.407464,0.750000,0.933594,381.0
31147,-24.782637892796757_-49.21201519318726_-24.625...,DOUTOR ULYSSES,-24.782638,-49.212015,-24.625378,-49.392223,"{'type': 'center_point', 'coordinates': [-24.7...",MULTIPOLYGON(((-49.4038750791893 -24.498103035...,POINT (-49.212015193187256 -24.78263789279676),412863305000007,873.0,-49.240663,-24.764145,RURAL,0.502978,0.716667,0.896348,220.0
31148,-24.774867509414683_-49.21201519318726_-24.625...,DOUTOR ULYSSES,-24.774868,-49.212015,-24.625378,-49.392223,"{'type': 'center_point', 'coordinates': [-24.7...",MULTIPOLYGON(((-49.4038750791893 -24.498103035...,POINT (-49.212015193187256 -24.774867509414683),412863305000007,873.0,-49.240663,-24.764145,RURAL,0.502978,0.716667,0.896348,220.0
31149,-24.76709712603261_-49.21201519318726_-24.6253...,DOUTOR ULYSSES,-24.767097,-49.212015,-24.625378,-49.392223,"{'type': 'center_point', 'coordinates': [-24.7...",MULTIPOLYGON(((-49.4038750791893 -24.498103035...,POINT (-49.212015193187256 -24.76709712603261),412863305000007,873.0,-49.240663,-24.764145,RURAL,0.502978,0.716667,0.896348,220.0
31150,-24.759326742650536_-49.21201519318726_-24.625...,DOUTOR ULYSSES,-24.759327,-49.212015,-24.625378,-49.392223,"{'type': 'center_point', 'coordinates': [-24.7...",MULTIPOLYGON(((-49.4038750791893 -24.498103035...,POINT (-49.212015193187256 -24.759326742650536),412863305000007,873.0,-49.240663,-24.764145,RURAL,0.502978,0.716667,0.896348,220.0

In [36]:
df_outer = df_vr[(~df_vr['Cod_setor'].isin(df['setor'].unique()))]

In [37]:
df_outer

,Unnamed: 0,Cod_setor,lat,long,TIPO,income,longevity,literacy,population
0,0,350270505000001,-48.848982,-24.513062,URBANO,0.606203,0.800000,0.970194,521.0
1,1,350270505000002,-48.846967,-24.511579,URBANO,0.671455,0.850000,0.971920,452.0
2,2,350270505000003,-48.845093,-24.514756,URBANO,0.778504,0.933333,0.975673,299.0
4,4,350270505000005,-48.841910,-24.522869,URBANO,0.545806,0.816667,0.968134,837.0
6,6,350270505000007,-48.849542,-24.515054,URBANO,0.609459,0.816667,0.970104,310.0
...,...,...,...,...,...,...,...,...,...
850,850,412220605000054,-49.302733,-25.215822,RURAL,0.504002,0.650000,0.891662,523.0
851,851,412220610000001,-49.482139,-24.989537,URBANO,0.564022,0.683333,0.969136,71.0
855,855,412788205000001,-49.087273,-24.972205,URBANO,0.573401,0.733333,0.855208,1082.0
860,860,412788205000006,-48.928630,-24.979127,RURAL,0.513213,0.783333,0.541950,553.0
865,865,412788205000011,-49.090760,-24.977358,URBANO,0.556493,0.683333,0.853725,538.0

In [35]:
df['setor'].unique()

array([350270530000002, 350270530000003, 350270530000001, 350270525000006,
       350270505000036, 350270525000005, 350270525000004, 350270505000028,
       350270505000038, 350270525000002, 350270505000040, 350270525000001,
       350270505000029, 350270510000004, 350270510000006, 350270505000006,
       350270510000003, 350270505000017, 350270505000004, 350270505000009,
       350270505000010, 350270505000030, 350270505000035, 350270505000034,
       350270505000011, 350270505000012, 350270505000039, 350270510000005,
       350270505000033, 350270505000031, 350270505000032, 350270505000037,
       350535105000009, 350535105000008, 350535105000007, 350535105000006,
       350535105000010, 350535105000004, 350535105000005, 350535105000011,
       350540105000008, 350540105000010, 350540105000007, 350540105000011,
       350540105000013, 350540105000012, 350540105000014, 350540105000009,
       350540105000001, 350540105000002, 350540105000004, 350540105000003,
       350540105000006, 350540105000005, 350540105000015, 352265305000005,
       352265305000007, 352265305000008, 352265305000004, 352265305000006,
       352265305000009, 352265305000001, 351480915000007, 351480915000005,
       351480915000012, 351480910000006, 351480915000009, 351480915000008,
       351480915000010, 351480910000003, 351480915000006, 351480910000005,
       351480915000004, 351480910000004, 351480910000008, 351480910000007,
       351480910000001, 351480910000002, 351480915000002, 351480915000003,
       351480905000015, 351480905000016, 351480915000001, 351480905000017,
       351480915000011, 351480905000010, 351480905000011, 351480905000007,
       351480905000008, 351480905000012, 351480905000003, 351480905000006,
       351480905000009, 351480905000002, 351480905000013, 351480905000014,
       352330505000022, 352330505000020, 352330505000016, 352330505000017,
       352330505000006, 352330505000013, 352330505000031, 352330505000039,
       352330505000038, 352330505000032, 352330505000005, 352330505000024,
       352330505000007, 352330505000023, 352330505000037, 352330505000004,
       352330505000025, 352330505000030, 352330505000029, 352330505000014,
       352330505000021, 352330505000036, 352330505000026, 352330505000010,
       352330505000015, 352330505000011, 352330505000028, 352330505000019,
       352330510000021, 352330510000020, 352330510000014, 352330510000005,
       352330510000015, 352330510000003, 352330510000019, 352330510000013,
       352330510000029, 352330510000023, 352330510000016, 352330510000001,
       352330510000012, 352330510000030, 352330510000011, 352330510000026,
       352330510000018, 352330510000017, 352330510000006, 352330510000008,
       352330510000007, 352330510000025, 352330510000009, 352610005000021,
       352610005000026, 352610005000031, 352610005000028, 352610005000027,
       352610005000033, 352610005000029, 352610005000020, 352610005000022,
       352610005000035, 352610005000032, 352610005000036, 352610005000017,
       352610005000006, 352610005000009, 352610005000002, 352610005000011,
       352610005000012, 352610005000018, 352610005000004, 352610005000034,
       352610005000005, 352610005000016, 352610005000023, 352610005000030,
       352610005000025, 352620910000011, 352620910000012, 352620910000003,
       352620905000041, 352620910000010, 352620910000004, 352620910000002,
       352620910000008, 352620910000007, 352620910000005, 352620905000027,
       352620905000020, 352620905000006, 352620910000009, 352620910000006,
       352620905000028, 352620905000040, 352620905000013, 352620905000001,
       352620905000007, 352620905000005, 352620905000017, 352620905000029,
       352620905000039, 352620905000012, 352620905000004, 352620905000002,
       352620905000003, 352620905000011, 352620905000015, 352620905000010,
       352620905000022, 352620905000038, 352620905000021, 352620905000036,
       352620905000037, 352620905000031, 352620905000025, 352620905000024,
       352620905000018, 352620905000043, 352620905000034, 352620905000042,
       352620905000023, 352620905000030, 352620905000035, 352620905000032,
       352620905000033, 410020205000006, 410020205000017, 410020205000016,
       410020205000015, 410020205000003, 410020205000014, 410020205000019,
       410020205000002, 410020205000004, 410020205000007, 410020205000008,
       410020205000010, 410020205000011, 410020205000013, 410020205000012,
       355350005000010, 355350005000009, 355350005000014, 355350005000012,
       355350005000013, 355350005000011, 355350005000008, 355350005000005,
       355350005000003, 355350005000004, 355350005000007, 355350005000001,
       355350005000002, 355350005000015, 355350005000006, 410310705000023,
       410310705000020, 410310705000006, 410310705000005, 410310705000019,
       410310705000007, 410310705000016, 410310705000003, 410310705000008,
       410310705000002, 410310705000004, 410310705000015, 410310705000011,
       410310705000009, 410310705000010, 410310705000014, 410310705000012,
       410310705000013, 410310705000017, 410310705000018, 411125805000020,
       411125805000025, 411125805000024, 411125805000019, 411125805000021,
       411125805000023, 411125805000022, 411125805000018, 411125805000034,
       411125805000017, 411125805000026, 411125805000033, 411125805000003,
       411125805000005, 411125805000016, 411125805000001, 411125805000030,
       411125805000009, 411125805000015, 411125805000010, 411125805000011,
       350990805000017, 350990810000006, 350990805000016, 350990810000002,
       350990810000003, 350990805000024, 350990805000018, 350990805000007,
       350990805000020, 350990805000019, 350990805000015, 350990805000025,
       350990805000021, 350990805000008, 350990805000022, 350990805000023,
       350990805000013, 350990805000011, 350990805000012, 350990805000005,
       350990805000014, 350990805000001, 350990805000002, 350990805000004,
       350925405000030, 350925405000031, 350925405000033, 350925405000034,
       350925405000029, 350925405000035, 350925405000037, 350925405000026,
       350925405000038, 350925405000027, 350925405000036, 350925405000021,
       350925405000039, 350925405000023, 350925405000022, 350925405000024,
       350925405000025, 350925405000007, 350925405000018, 350925405000006,
       350925405000008, 350925405000015, 350925405000013, 350925405000010,
       350925405000019, 350925405000012, 355180105000022, 355180105000015,
       355180105000017, 355180105000027, 355180105000019, 355180105000018,
       355180105000013, 355180105000014, 355180105000011, 355180105000010,
       355180105000009, 355180105000012, 355180105000008, 355180105000006,
       355180105000023, 355180105000026, 355180105000001, 355180105000002,
       355180105000007, 355180105000021, 355180105000025, 355180105000020,
       353620805000016, 353620805000017, 353620805000018, 353620805000019,
       353620805000025, 353620805000024, 353620805000007, 353620805000008,
       353620805000027, 353620805000015, 353620805000006, 353620805000001,
       353620805000002, 353620805000013, 353620805000028, 353620805000012,
       353620805000010, 353620805000009, 353620805000020, 353620805000014,
       353620805000022, 353620805000021, 353620805000023, 352030105000035,
       352030105000036, 352030105000056, 352030105000037, 352030105000019,
       352030105000038, 352030105000029, 352030105000034, 352030105000043,
       352030105000045, 352030105000018, 352030105000020, 352030105000044,
       352030105000039, 352030105000021, 352030105000061, 352030105000051,
       352030105000032, 352030105000011, 352030105000007, 352030105000057,
       352030105000046, 352030105000010, 352030105000030, 352030105000047,
       352030105000054, 352030105000022, 352030105000058, 352030105000040,
       352030105000028, 352030105000027, 352030105000041, 352030105000049,
       352030105000033, 352030105000048, 352030105000026, 352030105000053,
       352030105000064, 352030105000059, 352030105000065, 352030105000025,
       352030105000042, 352030105000060, 352042605000006, 352042605000005,
       352042605000012, 352042605000007, 352042605000010, 352042605000008,
       352042605000018, 352042605000017, 352042605000030, 352042605000009,
       352042605000016, 352042605000028, 352042605000029, 352042605000004,
       352042605000003, 352042605000019, 352042605000020, 352042605000025,
       352042605000031, 352042605000024, 352042605000002, 352042605000014,
       352042605000021, 352042605000022, 352042605000015, 352042605000026,
       352042605000027, 352120005000011, 352120005000012, 352120005000013,
       352120005000010, 352120005000021, 352120005000005, 352120005000009,
       352120005000014, 352120005000006, 352120005000007, 352120005000008,
       352120005000019, 352120005000017, 352120005000020, 352120005000015,
       352120005000016, 352120005000018, 354260205000062, 354260205000063,
       354260205000061, 354260205000064, 354260205000048, 354260205000049,
       354260205000055, 354260205000045, 354260205000046, 354260205000037,
       354260205000060, 354260205000033, 354260205000034, 354260205000050,
       354260205000027, 354260205000054, 354260205000021, 354260205000023,
       354260205000026, 354260205000069, 354260205000032, 354260205000019,
       354260205000006, 354260205000002, 354260205000016, 354260205000012,
       354260205000051, 354260205000041, 354260205000066, 354260205000013,
       354260205000043, 354260205000042, 354260205000039, 354260205000068,
       354260205000030, 354260205000028, 354260205000029, 354260205000053,
       354260205000059, 354260205000052, 354260205000047, 354260205000058,
       354260205000056, 354260205000057, 354280005000008, 354280005000004,
       354280005000005, 354280005000006, 354280005000007, 352215805000008,
       352215805000009, 352215805000004, 352215805000005, 352215805000007,
       352215805000001, 352215805000002, 352215805000003, 352460005000022,
       352460005000019, 352460005000020, 352460005000012, 352460005000018,
       352460005000013, 352460005000021, 352460005000027, 352460005000026,
       352460005000011, 352460005000017, 352460005000014, 352460005000023,
       352460005000009, 352460005000003, 352460005000005, 352460005000010,
       352460005000016, 352460005000002, 352460005000015, 352990608000002,
       352990608000005, 352990608000003, 352990608000001, 352990605000025,
       352990605000024, 352990605000017, 352990605000026, 352990605000012,
       352990605000011, 352990605000023, 352990605000016, 352990605000013,
       352990605000008, 352990605000022, 352990605000001, 352990605000002,
       352990605000019, 352990605000009, 352990605000015, 352990610000007,
       352990605000014, 352990605000018, 352990610000006, 352990605000021,
       352990615000006, 352990610000005, 352990610000001, 352990615000007,
       352990615000008, 352990610000003, 352990610000004, 352990605000020,
       352990610000002, 352990615000002, 352990610000009, 352990615000001,
       352990615000003, 352990615000005, 352990615000004, 353720605000011,
       353720605000010, 353720605000015, 353720605000007, 353720605000008,
       353720605000012, 353720605000005, 353720605000017, 353720605000002,
       353720605000014, 353720605000004, 353720605000009, 353720605000016,
       353720605000001, 353720605000013, 354995305000014, 354995305000023,
       354995305000005, 354995305000015, 354995305000006, 354995305000007,
       354995305000016, 354995305000013, 354995305000008, 354995305000027,
       354995305000004, 354995305000020, 354995305000022, 354995305000001,
       354995305000012, 354995305000011, 354995305000009, 354995305000019,
       354995305000010, 354995305000024, 354995305000026, 354995305000025,
       354995305000017, 354995305000018, 410520110000004, 410520110000005,
       410520110000003, 410520110000006, 410520110000002, 410520110000011,
       410520110000010, 410520110000007, 410520105000010, 410520105000011,
       410520110000009, 410520110000008, 410520105000009, 410520105000012,
       410520105000013, 410520105000023, 410520105000014, 410520105000026,
       410520105000024, 410520105000008, 410520105000007, 410520105000022,
       410520105000031, 410520105000015, 410520105000029, 410520105000005,
       410520105000001, 410520105000030, 410520105000027, 410520105000003,
       410520105000002, 410520105000006, 410520105000020, 410520105000017,
       410520105000021, 410520105000016, 410520105000018, 410520105000019,
       410520105000025, 412220610000002, 412220610000003, 412220610000004,
       412220605000027, 412220605000028, 412220605000029, 412220605000030,
       412220605000026, 412220605000032, 412220605000031, 412220605000024,
       412220605000025, 412220605000033, 412220605000034, 412220605000035,
       412220605000011, 412220605000003, 412220605000022, 412220605000045,
       412220605000009, 412220605000004, 412220605000012, 412220605000017,
       412220605000019, 412220605000053, 412220605000008, 412220605000048,
       412220605000006, 412220605000023, 412220605000044, 412220605000050,
       412220605000020, 412220605000041, 412220605000043, 412220605000042,
       412220605000046, 412220605000040, 412220605000039, 412220605000036,
       412220605000038, 412220605000037, 412788205000003, 412788205000012,
       412788205000005, 412788205000004, 412788205000002, 412788205000007,
       412788205000009, 412788205000008, 412788205000010, 412863305000013,
       412863305000012, 412863305000002, 412863305000011, 412863305000004,
       412863305000010, 412863305000001, 412863305000003, 412863305000009,
       412863305000005, 412863305000008, 412863305000006, 412863305000007])

In [48]:
df_vr_unique = df_vr.drop_duplicates(subset=['Cod_setor'])

In [50]:
df_vr_unique.nunique()

Unnamed: 0    880
Cod_setor     880
lat           880
long          880
TIPO            2
income        880
longevity      34
literacy      866
population    624
dtype: int64

In [46]:
df_unique = df.drop_duplicates(subset=['setor'])

In [51]:
df_unique.nunique()

image_name     732
NM_MUNICIP      30
image_lat      453
image_lon      471
cluster_lat     30
cluster_lon     30
features       732
area            30
geometry       732
setor          732
Unnamed: 0     672
lat            672
long           672
TIPO             2
income         672
longevity       34
literacy       662
population     510
dtype: int64

In [70]:
df_outer = pd.merge(df_vr, df, left_on='Cod_setor', right_on='setor', how="outer", indicator=True)
df_not_picture = df_outer[df_outer['_merge'] == 'left_only']
df_not_data = df_outer[df_outer['_merge'] == 'right_only']

In [71]:
df_not_picture

,Unnamed: 0_x,Cod_setor,lat_x,long_x,TIPO_x,income_x,longevity_x,literacy_x,population_x,image_name,...,setor,Unnamed: 0_y,lat_y,long_y,TIPO_y,income_y,longevity_y,literacy_y,population_y,_merge
0,0.0,3.502705e+14,-48.848982,-24.513062,URBANO,0.606203,0.800000,0.970194,521.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,1.0,3.502705e+14,-48.846967,-24.511579,URBANO,0.671455,0.850000,0.971920,452.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,2.0,3.502705e+14,-48.845093,-24.514756,URBANO,0.778504,0.933333,0.975673,299.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,4.0,3.502705e+14,-48.841910,-24.522869,URBANO,0.545806,0.816667,0.968134,837.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
7,6.0,3.502705e+14,-48.849542,-24.515054,URBANO,0.609459,0.816667,0.970104,310.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27170,850.0,4.122206e+14,-49.302733,-25.215822,RURAL,0.504002,0.650000,0.891662,523.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
27171,851.0,4.122206e+14,-49.482139,-24.989537,URBANO,0.564022,0.683333,0.969136,71.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
27273,855.0,4.127882e+14,-49.087273,-24.972205,URBANO,0.573401,0.733333,0.855208,1082.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
27526,860.0,4.127882e+14,-48.928630,-24.979127,RURAL,0.513213,0.783333,0.541950,553.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
28176,865.0,4.127882e+14,-49.090760,-24.977358,URBANO,0.556493,0.683333,0.853725,538.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [72]:
df_not_data

,Unnamed: 0_x,Cod_setor,lat_x,long_x,TIPO_x,income_x,longevity_x,literacy_x,population_x,image_name,...,setor,Unnamed: 0_y,lat_y,long_y,TIPO_y,income_y,longevity_y,literacy_y,population_y,_merge
29239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-24.508113468980746_-48.728304686680346_-24.42...,...,3.502705e+14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
29240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-24.515912057096592_-48.719791718690104_-24.42...,...,3.502705e+14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
29241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-24.508113468980746_-48.719791718690104_-24.42...,...,3.502705e+14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
29242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-24.5003148808649_-48.719791718690104_-24.4214...,...,3.502705e+14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
29243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-24.508113468980746_-48.711278750699854_-24.42...,...,3.502705e+14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-24.34988514504788_-47.33800320056303_-24.1950...,...,3.529906e+14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
31355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-24.342066287226437_-47.33800320056303_-24.195...,...,3.529906e+14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
31356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-24.334247429404993_-47.33800320056303_-24.195...,...,3.529906e+14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
31357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-24.342066287226437_-47.32956845533142_-24.195...,...,3.529906e+14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
31358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-24.342066287226437_-47.32113371009981_-24.195...,...,3.529906e+14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only

In [78]:
df[df['income'].isna()]['setor'].nunique()

60

In [ ]:
def find_setor(row):
 
    for _, setor in vale.iterrows():
        if row['geometry'].within(setor['geometry']):
            return setor['CD_GEOCODI']
    else:
        return np.nan
    
geo['setor'] = geo.apply(find_setor, axis=1)